#!/bin/bash

git checkout main
git checkout -- .
git tag -d 0
git branch -D demo
git checkout -b demo
git checkout dev .vscode
echo >>.gitignore
echo './history'>>.gitignore
git add -A
git commit -am "tools"
git tag 0
git checkout dev history
git checkout dev sample
git checkout dev package.json
git checkout dev package-lock.json
git restore --staged *
git status
mkdir src
git add -A
git status 
git commit -am "sample"


for var in history/*
do
    echo "$var"
    rm -fr ./src/*
    cp -r $var/* ./src/
    message=`cat ./src/COMMIT_MESSAGE`
    rm ./src/COMMIT_MESSAGE
    git add ./src
    git commit -am "$message"
done

rm -fr history
git checkout 0


